name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
          fetch-depth: 0 # Full clone to ensure all files are available
      - name: List Files for Debugging
        run: |
          echo "Listing files in workspace:"
          ls -la
          echo "Checking for staticwebapp.config.json:"
          if [ -f staticwebapp.config.json ]; then
            echo "Found staticwebapp.config.json"
          else
            echo "staticwebapp.config.json NOT found"
          fi
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Compatible with Vite 5.1.4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Copy staticwebapp.config.json to dist
        run: |
          if [ -f staticwebapp.config.json ]; then
            cp staticwebapp.config.json dist/
            echo "Copied staticwebapp.config.json to dist/"
          else
            echo "staticwebapp.config.json not found, skipping."
          fi
      - name: Verify dist Contents
        run: |
          echo "Listing files in dist:"
          ls -la dist/
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_COAST_0A8AAD800 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_COAST_0A8AAD800 }}
          action: "close"
